### PR TITLE
Added tests

### PR DESCRIPTION
**Pull request by akaNightmare**
1. added v8 compiling for < 8 nodejs
2. added TravicCI

### CODE REVIEW

**Comment by akaNightmare** [comment]
@damirn please add this project to the TravisCI

**Comment by damirn** [comment]
please add yourself to the contributors list, thanks

**Comment by akaNightmare** [comment]
@damirn added

**Comment by damirn** [comment]
I had to push a small fix for clang / mac os x. can you check if this now works on linux and/or windows? thanks

**Comment by akaNightmare** [comment]
@damirn will check it, also I can add osx & windows to the travis CI, are you ok with that?

**Comment by damirn** [comment]
yes, that would be great

**Comment by akaNightmare** [comment]
@damirn https://travis-ci.org/akaNightmare/rapidx2j/builds/479286386?utm_source=github_status&utm_medium=notification

**Comment by damirn** [comment]
so it seems that all windows builds fail :( i'll check what's wrong with
mac os x with older node.js versions.

**Comment by akaNightmare** [comment]
@damirn could you publish the latest changes?

**Comment by damirn** [comment]
I will

**Comment by akaNightmare** [comment]
@damirn please publish new version of the lib

**Comment by damirn** [comment]
i published it couple of days ago, v0.5.0

**Comment by akaNightmare** [comment]
@damirn with the latest changes ?

**Comment by damirn** [comment]
yep; check it out

**Pull request merged**
